language: php
sudo: false

git:
  depth: 2

matrix:
  include:
    - php: 7.0
      env:
        - COVERAGE=true
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable

before_script:
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer update --no-interaction --prefer-source --prefer-stable --classmap-authoritative

script:
  - composer run-all
  - composer run-sa-junit
  - if [[ "$COVERAGE" == "true" ]]; then
      xdebug-enable;
      vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover;
      xdebug-disable;
    fi

after_script:
  - if [[ "$COVERAGE" == "true" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
